[package]
name = "form_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.47"
quote = "1.0.21"
syn = { version = "1", features = ["full"] }
form = { version = "0.1", path = "../form" }